# Generated by Django 5.0.4 on 2024-05-02 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuredusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.IntegerField()),
                ('apartment_number', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=20)),
                ('insured_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='insuredusers.insureduser')),
            ],
        ),
    ]
