# Generated by Django 5.0.4 on 2024-05-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurances', '0002_typeofinsurance_alter_insurance_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
